"""Add candidate decision and outbound email tables.

Revision ID: 20260224_0002
Revises: 20260224_0001
Create Date: 2026-02-24 01:30:00
"""

from __future__ import annotations

from alembic import op


revision = "20260224_0002"
down_revision = "20260224_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS candidate_decisions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            candidate_id TEXT NOT NULL REFERENCES candidates(id),
            position_id TEXT NOT NULL REFERENCES positions(id),
            client_id TEXT NOT NULL REFERENCES clients(id),
            decision TEXT NOT NULL,
            reason TEXT,
            decided_by_session TEXT,
            decided_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS outbound_emails (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            candidate_id TEXT NOT NULL REFERENCES candidates(id),
            client_id TEXT NOT NULL REFERENCES clients(id),
            subject TEXT NOT NULL,
            body TEXT NOT NULL,
            status TEXT DEFAULT 'queued',
            provider TEXT DEFAULT 'mock',
            created_by_session TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )


def downgrade() -> None:
    # Keep downgrade non-destructive for shared environments.
    pass
