"""Add idempotency keys to decisions/emails and an audit_events table.

Revision ID: 20260514_0004
Revises: 20260224_0003
Create Date: 2026-05-14 22:00:00
"""

from __future__ import annotations

from alembic import op


revision = "20260514_0004"
down_revision = "20260224_0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE candidate_decisions
            ADD COLUMN IF NOT EXISTS idempotency_key TEXT
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS ux_candidate_decisions_idempotency_key
            ON candidate_decisions (idempotency_key)
            WHERE idempotency_key IS NOT NULL
        """
    )
    op.execute(
        """
        ALTER TABLE outbound_emails
            ADD COLUMN IF NOT EXISTS idempotency_key TEXT
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS ux_outbound_emails_idempotency_key
            ON outbound_emails (idempotency_key)
            WHERE idempotency_key IS NOT NULL
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS audit_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id TEXT,
            client_id TEXT NOT NULL,
            actor TEXT NOT NULL DEFAULT 'agent',
            tool TEXT NOT NULL,
            action TEXT NOT NULL,
            target_id TEXT,
            payload_hash TEXT,
            outcome TEXT NOT NULL DEFAULT 'ok',
            error TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_audit_events_client_created
            ON audit_events (client_id, created_at DESC)
        """
    )


def downgrade() -> None:
    # Keep downgrade non-destructive for shared environments.
    pass
