"""Baseline PostgreSQL schema and compatibility columns.

Revision ID: 20260224_0001
Revises:
Create Date: 2026-02-24 01:10:00
"""

from __future__ import annotations

from alembic import op


revision = "20260224_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS clients (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            industry TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS positions (
            id TEXT PRIMARY KEY,
            client_id TEXT NOT NULL REFERENCES clients(id),
            title TEXT NOT NULL,
            description TEXT,
            status TEXT DEFAULT 'open',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS hiring_rubrics (
            id TEXT PRIMARY KEY,
            position_id TEXT NOT NULL REFERENCES positions(id),
            client_id TEXT NOT NULL REFERENCES clients(id),
            criteria TEXT NOT NULL,
            scoring_notes TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS candidates (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            email TEXT UNIQUE,
            resume_hash TEXT,
            resume_text TEXT,
            linkedin_url TEXT,
            website_url TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS evaluations (
            id TEXT PRIMARY KEY,
            candidate_id TEXT NOT NULL REFERENCES candidates(id),
            position_id TEXT NOT NULL REFERENCES positions(id),
            client_id TEXT NOT NULL REFERENCES clients(id),
            technical_score REAL,
            experience_score REAL,
            culture_score REAL,
            communication_score REAL,
            overall_score REAL,
            reasoning TEXT,
            recommendation TEXT,
            evaluated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS agent_memory (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id TEXT NOT NULL,
            client_id TEXT NOT NULL,
            memory_key TEXT NOT NULL,
            memory_value TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    # Compatibility columns expected by agent-generated insert/update payloads.
    op.execute("ALTER TABLE candidates ADD COLUMN IF NOT EXISTS phone TEXT")
    op.execute("ALTER TABLE candidates ADD COLUMN IF NOT EXISTS skills TEXT")
    op.execute("ALTER TABLE candidates ADD COLUMN IF NOT EXISTS experience TEXT")
    op.execute("ALTER TABLE candidates ADD COLUMN IF NOT EXISTS education TEXT")
    op.execute("ALTER TABLE candidates ADD COLUMN IF NOT EXISTS linkedin_data TEXT")
    op.execute("ALTER TABLE candidates ADD COLUMN IF NOT EXISTS website_data TEXT")
    op.execute("ALTER TABLE candidates ADD COLUMN IF NOT EXISTS score REAL")
    op.execute("ALTER TABLE candidates ADD COLUMN IF NOT EXISTS notes TEXT")
    op.execute("ALTER TABLE candidates ADD COLUMN IF NOT EXISTS client_id TEXT")
    op.execute(
        """
        ALTER TABLE candidates
        ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        """
    )

    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'fk_candidates_client_id'
            ) THEN
                ALTER TABLE candidates
                ADD CONSTRAINT fk_candidates_client_id
                FOREIGN KEY (client_id) REFERENCES clients(id);
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    # Keep downgrade non-destructive for shared environments.
    pass
