"""Database schema creation and teardown."""

from pathlib import Path
from typing import Set

from src.database.db import get_db, get_db_url


CREATE_TABLES_SQL = """
CREATE TABLE IF NOT EXISTS clients (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    industry TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS positions (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE IF NOT EXISTS hiring_rubrics (
    id TEXT PRIMARY KEY,
    position_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    criteria TEXT NOT NULL,
    scoring_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (position_id) REFERENCES positions(id),
    FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE IF NOT EXISTS candidates (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT,
    skills TEXT,
    experience TEXT,
    education TEXT,
    resume_hash TEXT,
    resume_text TEXT,
    linkedin_url TEXT,
    linkedin_data TEXT,
    website_url TEXT,
    website_data TEXT,
    score REAL,
    notes TEXT,
    client_id TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE IF NOT EXISTS evaluations (
    id TEXT PRIMARY KEY,
    candidate_id TEXT NOT NULL,
    position_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    technical_score REAL,
    experience_score REAL,
    culture_score REAL,
    communication_score REAL,
    overall_score REAL,
    reasoning TEXT,
    recommendation TEXT,
    evaluated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (candidate_id) REFERENCES candidates(id),
    FOREIGN KEY (position_id) REFERENCES positions(id),
    FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE IF NOT EXISTS candidate_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id TEXT NOT NULL,
    position_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    decision TEXT NOT NULL,
    reason TEXT,
    decided_by_session TEXT,
    decided_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (candidate_id) REFERENCES candidates(id),
    FOREIGN KEY (position_id) REFERENCES positions(id),
    FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE IF NOT EXISTS outbound_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    status TEXT DEFAULT 'queued',
    provider TEXT DEFAULT 'mock',
    created_by_session TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (candidate_id) REFERENCES candidates(id),
    FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE IF NOT EXISTS agent_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    memory_key TEXT NOT NULL,
    memory_value TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

DROP_TABLES_SQL = """
DROP TABLE IF EXISTS agent_memory;
DROP TABLE IF EXISTS outbound_emails;
DROP TABLE IF EXISTS candidate_decisions;
DROP TABLE IF EXISTS evaluations;
DROP TABLE IF EXISTS candidates;
DROP TABLE IF EXISTS hiring_rubrics;
DROP TABLE IF EXISTS positions;
DROP TABLE IF EXISTS clients;
"""

ALEMBIC_VERSION_TABLE = "hr_ai_alembic_version"


def init_db() -> None:
    """Create all database tables for Phase 1."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(CREATE_TABLES_SQL)
    print("Database initialized successfully.")


def run_migrations() -> None:
    """Apply Alembic migrations up to head with recovery for foreign revision chains."""
    from alembic import command
    from alembic.config import Config
    from alembic.script import ScriptDirectory
    from alembic.util.exc import CommandError
    from sqlalchemy import create_engine, text

    repo_root = Path(__file__).resolve().parents[2]
    alembic_ini = repo_root / "alembic.ini"
    cfg = Config(str(alembic_ini))
    cfg.set_main_option("script_location", str(repo_root / "alembic"))

    script = ScriptDirectory.from_config(cfg)
    heads: Set[str] = set(script.get_heads())

    current: Set[str] = set()
    engine = create_engine(get_db_url())
    with engine.connect() as conn:
        table_ref = conn.execute(text(f"SELECT to_regclass('public.{ALEMBIC_VERSION_TABLE}')")).scalar()
        if table_ref:
            rows = conn.execute(text(f"SELECT version_num FROM {ALEMBIC_VERSION_TABLE}")).fetchall()
            current = {str(row[0]) for row in rows}

    if heads and current == heads:
        return

    try:
        command.upgrade(cfg, "head")
    except CommandError as exc:
        # Shared Neon instances may contain a foreign alembic chain from another service.
        if "Can't locate revision identified by" not in str(exc):
            raise

        with engine.begin() as conn:
            conn.execute(text(f"DROP TABLE IF EXISTS {ALEMBIC_VERSION_TABLE}"))
        command.upgrade(cfg, "head")


def drop_all_tables() -> None:
    """Drop all database tables in reverse dependency order."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(DROP_TABLES_SQL)
